--- n/coff2noff/Makefile	2002-12-16 17:57:00.000000000 +0700
+++ NachOS-4.0/coff2noff/Makefile	2021-06-10 17:24:22.660288606 +0700
@@ -28,10 +28,10 @@
 include Makefile.dep
 
 CC=gcc
-CFLAGS= $(HOSTCFLAGS) -DRDATA
-LD=gcc
+CFLAGS= $(HOSTCFLAGS) -DRDATA -m32
+LD=gcc -m32
 RM = /bin/rm
-MV = /usr/bin/mv
+MV = /bin/mv
 
 ifeq ($(hosttype),unknown)
 buildtargets = unknownhost
